version: "3.9"
services:
  web:
    build: app/aspnetapp
    ports:
      - 80:80
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    restart: always
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Complex123Password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Complex123Password' -Q 'SELECT 1' || exit 1"]
    
